config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :chats, only: [:index, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat = Chat.new
    @room = Room.find(params[:room_id])
    @chats = @room.chats.includes(:user)
  end
  def create
    @room = Room.find(params[:room_id])
    @chat = @room.chats.new(chat_params)
    
    if @chat.save
      redirect_to room_chats_path(@room)
    else
      @chats = @room.chats.includes(:user)
      render :index
    end
  end

  private
  def chat_params
    params.require(:chat).permit(:content).merge(user_id: current_user.id)
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= chat.user.nickname %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l chat.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= chat.content%>
    </div>
    <%# <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/chats/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "チャット終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>


<div class="messages">
  <%= render partial: 'chat', collection: @chats %>
</div>
<%= form_with model: [@room, @chat], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <%# <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    <%# </label> %> 
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/chats/_side_bar.html.erb
<div class="side-bar-header">
  <div class="user-name" >
    <%# <%= link_to current_user.nickname, edit_user_path(current_user) %>
    <%= current_user.nickname %>
  </div>
  <div class="top-link">
    <%= link_to "connect", root_path %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
  <div class="room">
    <div class="room-name">
      <%= link_to room.name, room_chats_path(room) %>
    </div>
  </div>
  <% end %>
</div>

app/views/chats/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="main-bar">
    <%= render "main_chat" %>
  </div>

</div>